//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyCuaHangEntities : DbContext
    {
        public QuanLyCuaHangEntities()
            : base("name=QuanLyCuaHang3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Input> Input { get; set; }
        public virtual DbSet<InputInfo> InputInfo { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Output> Output { get; set; }
        public virtual DbSet<OutputInfo> OutputInfo { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<Suplier> Suplier { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
